
LIBNAME=js
SRCS=jsapi.c jsarena.c jsarray.c jsatom.c jsbool.c jscntxt.c jsdate.c jsdbgapi.c jsdhash.c jsdtoa.c	jsemit.c	jsexn.c		jsfun.c		jsgc.c		jshash.c	jsinterp.c	jsinvoke.c	jsiter.c	jslock.c	jslog2.c	jslong.c	jsmath.c	jsnum.c		jsobj.c		jsopcode.c      jsparse.c	jsprf.c		jsregexp.c	jsscan.c	jsscope.c	jsscript.c	jsstr.c		jsutil.c        jsxdrapi.c	jsxml.c		prmjtime.c	

include ../../Makefile.sd
