
DEBUG?=yes
DEBUG_MEM?=yes
PTHREADS?=yes
DYNAMIC?=yes
SHARED?=no
STATIC?=no
PAHO?=yes
ID:=$(shell id -u)

ifneq "$(findstring win,$(TARGET))" ""
ISWIN=yes
endif

ifeq ($(ID),0)
INSTALL_USER=-o root -g root
PREFIX?=/opt/sd
else
PREFIX?=$(shell echo $$HOME)
endif

# Define SRC_ROOT
current_makefile := $(lastword $(MAKEFILE_LIST))
SRC_ROOT=$(shell echo $$(dirname $(current_makefile)))

CFLAGS+=-I.

# Uses libsmanet? must be included before libsolard as it refs
ifeq ($(SMANET),yes)
	CFLAGS+=-I$(SRC_ROOT)/smanet
	LIBS+=-L$(SRC_ROOT)/smanet -lsmanet$(SUFFIX)
	DEPS+=$(SRC_ROOT)/smanet/libsmanet$(SUFFIX)$(LIBEXT)
endif

ifeq ($(OLDSMANET),yes)
	CFLAGS+=-I$(SRC_ROOT)/oldsmanet
	LIBS+=-L$(SRC_ROOT)/oldsmanet -loldsmanet$(SUFFIX)
	DEPS+=$(SRC_ROOT)/oldsmanet/liboldsmanet$(SUFFIX)$(LIBEXT)
endif

ifeq ($(JBD),yes)
	CFLAGS+=-I$(SRC_ROOT)/jbd
	LIBS+=-L$(SRC_ROOT)/jbd -ljbd$(SUFFIX)
	DEPS+=$(SRC_ROOT)/jbd/libjbd$(SUFFIX)$(LIBEXT)
endif

ifneq ($(LIBNAME),solard)
CFLAGS+=-I$(SRC_ROOT)/lib
LIBS+=-L$(SRC_ROOT)/lib -lsolard$(SUFFIX)
DEPS+=$(SRC_ROOT)/lib/libsolard$(SUFFIX)$(LIBEXT)
endif

# Paho MQTT
ifeq ($(PAHO),yes)
ifeq ($(STATIC),yes)
_PAHOLDADD=-lssl -lcrypto -lz
ifeq ($(TARGET),win32)
_PAHOSTATIC=-static
_PAHOLDADD+=-lgdi32 -lcrypt32
endif
endif
LIBS+=-lpaho-mqtt3cs$(_PAHOSTATIC) $(_PAHOLDADD)
endif

# Include transports
SRCS+=$(shell IFS=","; for i in $(TRANSPORTS); do printf "%s.c " $${i}; done)
CFLAGS+=-I$(SRC_ROOT)/transports
vpath %.c $(SRC_ROOT)/transports

ifneq "$(findstring bluetooth,$(TRANSPORTS))" ""
BLUETOOTH=yes
endif
ifneq "$(findstring bt,$(TRANSPORTS))" ""
BLUETOOTH=yes
endif

# Bluetooth
ifeq ($(BLUETOOTH),yes)
ifneq ($(ISWIN),yes)
CFLAGS+=-DBLUETOOTH
#LIBS+=-lgattlib -ldbus-1 -lgobject-2.0 -lglib-2.0 -lgio-2.0
LIBS+=-lgattlib -lglib-2.0 -lgobject-2.0 -lgio-2.0
#LIBS+=-lgattlib -lglib-2.0
endif
endif

ifneq "$(findstring http,$(TRANSPORTS))" ""
LIBS+=-lcurl
endif

include $(SRC_ROOT)/Makefile.inc
