#define SOLARD_AGENTINFO_PROPIDS \
	SOLARD_AGENTINFO_PROPERTY_ID_INDEX=101, \
	SOLARD_AGENTINFO_PROPERTY_ID_ID=102, \
	SOLARD_AGENTINFO_PROPERTY_ID_AGENT=103, \
	SOLARD_AGENTINFO_PROPERTY_ID_PATH=104, \
	SOLARD_AGENTINFO_PROPERTY_ID_ROLE=105, \
	SOLARD_AGENTINFO_PROPERTY_ID_NAME=106, \
	SOLARD_AGENTINFO_PROPERTY_ID_TRANSPORT=107, \
	SOLARD_AGENTINFO_PROPERTY_ID_TARGET=108, \
	SOLARD_AGENTINFO_PROPERTY_ID_TOPTS=109, \
	SOLARD_AGENTINFO_PROPERTY_ID_MANAGED=110, \
	SOLARD_AGENTINFO_PROPERTY_ID_STATE=111, \
	SOLARD_AGENTINFO_PROPERTY_ID_STARTED=112, \
	SOLARD_AGENTINFO_PROPERTY_ID_MAX
