
PROGNAME=jbd
SRCS=main.c io.c read.c info.c config.c control.c
#TRANSPORTS=ip.c serial.c can.c

#BLUETOOTH=yes

include ../../Makefile.sd
#LIBS+=$(shell krb5-config --libs)
#LIBS+=-L/usr/lib64/heimdal -lkrb5 -lhcrypto -lhx509 -lasn1 -lheimbase -lroken -lsqlite3
