
PROGNAME=jbd
SRCS=main.c jbd.c config.c info.c jsfuncs.c
SCRIPTS=*.js

#BLUETOOTH=yes

include ../../Makefile.sd
#LIBS+=$(shell krb5-config --libs)
#LIBS+=-L/usr/lib64/heimdal -lkrb5 -lhcrypto -lhx509 -lasn1 -lheimbase -lroken -lsqlite3
