
LIBNAME=$(shell basename $(shell pwd))
SRCS=init.c debug.c opts.c log.c utils.c getpath.c memory.c daemon.c driver.c homedir.c list.c types.c conv.c json.c parson.c cfg.c mqtt.c uuid.c message.c findconf.c buffer.c tmpdir.c exec.c agent.c client.c fork.c ic.c config.c script.c

include ../Makefile.sd
