
DEBUG=yes

PROG=$(shell basename $(shell pwd))
SRCS=main.c config.c db.c battery.c display.c
OBJS=$(SRCS:.c=.o)
CFLAGS=-I../lib
LIBS=-L../lib -lsolard -lpaho-mqtt3c

include ../Makefile.inc

.PHONY: all install
all: $(PROG)

$(PROG): $(OBJS) $(DEPS)
	$(CC) $(CFLAGS) $(LDFLAGS) -o $(PROG) $(OBJS) $(LIBS)

$(OBJS): Makefile

include ../Makefile.dep

debug: $(PROG)
	gdb $(PROG)

install: $(PROG)
	install -m 755 -o bin -g bin $(PROG) /usr/local/bin

clean:
	rm -rf $(PROG) $(OBJS) $(CLEANFILES)

push: clean
	git add -A .
	git commit -m refresh
	git push

pull: clean
	git reset --hard
	git pull
