//unhandled: si_power_t grid
//unhandled: si_power_t si
//unhandled: si_power_t grid
//unhandled: si_power_t si
//unhandled: si_power_t volt
		{ "output_voltage", DATA_TYPE_FLOAT, &s->info.voltage, 0, 0, CONFIG_FLAG_READONLY | CONFIG_FLAG_NOSAVE },
		{ "output_frequency", DATA_TYPE_FLOAT, &s->info.frequency, 0, 0, CONFIG_FLAG_READONLY | CONFIG_FLAG_NOSAVE },
		{ "output_current", DATA_TYPE_FLOAT, &s->info.ac1_current, 0, 0, CONFIG_FLAG_READONLY | CONFIG_FLAG_NOSAVE },
		{ "battery_voltage", DATA_TYPE_FLOAT, &s->info.battery_voltage, 0, 0, CONFIG_FLAG_READONLY | CONFIG_FLAG_NOSAVE },
		{ "battery_current", DATA_TYPE_FLOAT, &s->info.battery_current, 0, 0, CONFIG_FLAG_READONLY | CONFIG_FLAG_NOSAVE },
		{ "battery_temp", DATA_TYPE_FLOAT, &s->info.battery_temp, 0, 0, CONFIG_FLAG_READONLY | CONFIG_FLAG_NOSAVE },
		{ "battery_soc", DATA_TYPE_FLOAT, &s->info.battery_soc, 0, 0, CONFIG_FLAG_READONLY | CONFIG_FLAG_NOSAVE },
		{ "battery_soh", DATA_TYPE_FLOAT, &s->info.battery_soh, 0, 0, CONFIG_FLAG_READONLY | CONFIG_FLAG_NOSAVE },
		{ "battery_cvsp", DATA_TYPE_FLOAT, &s->info.battery_cvsp, 0, 0, CONFIG_FLAG_READONLY | CONFIG_FLAG_NOSAVE },
		{ "relay1", DATA_TYPE_BOOL, &s->info.relay1, 0, 0, CONFIG_FLAG_READONLY | CONFIG_FLAG_NOSAVE },
		{ "relay2", DATA_TYPE_BOOL, &s->info.relay2, 0, 0, CONFIG_FLAG_READONLY | CONFIG_FLAG_NOSAVE },
		{ "s1_relay1", DATA_TYPE_BOOL, &s->info.s1_relay1, 0, 0, CONFIG_FLAG_READONLY | CONFIG_FLAG_NOSAVE },
		{ "s1_relay2", DATA_TYPE_BOOL, &s->info.s1_relay2, 0, 0, CONFIG_FLAG_READONLY | CONFIG_FLAG_NOSAVE },
		{ "s2_relay1", DATA_TYPE_BOOL, &s->info.s2_relay1, 0, 0, CONFIG_FLAG_READONLY | CONFIG_FLAG_NOSAVE },
		{ "s2_relay2", DATA_TYPE_BOOL, &s->info.s2_relay2, 0, 0, CONFIG_FLAG_READONLY | CONFIG_FLAG_NOSAVE },
		{ "s3_relay1", DATA_TYPE_BOOL, &s->info.s3_relay1, 0, 0, CONFIG_FLAG_READONLY | CONFIG_FLAG_NOSAVE },
		{ "s3_relay2", DATA_TYPE_BOOL, &s->info.s3_relay2, 0, 0, CONFIG_FLAG_READONLY | CONFIG_FLAG_NOSAVE },
		{ "GnRn", DATA_TYPE_BOOL, &s->info.GnRn, 0, 0, CONFIG_FLAG_READONLY | CONFIG_FLAG_NOSAVE },
		{ "s1_GnRn", DATA_TYPE_BOOL, &s->info.s1_GnRn, 0, 0, CONFIG_FLAG_READONLY | CONFIG_FLAG_NOSAVE },
		{ "s2_GnRn", DATA_TYPE_BOOL, &s->info.s2_GnRn, 0, 0, CONFIG_FLAG_READONLY | CONFIG_FLAG_NOSAVE },
		{ "s3_GnRn", DATA_TYPE_BOOL, &s->info.s3_GnRn, 0, 0, CONFIG_FLAG_READONLY | CONFIG_FLAG_NOSAVE },
		{ "AutoGn", DATA_TYPE_BOOL, &s->info.AutoGn, 0, 0, CONFIG_FLAG_READONLY | CONFIG_FLAG_NOSAVE },
		{ "AutoLodExt", DATA_TYPE_BOOL, &s->info.AutoLodExt, 0, 0, CONFIG_FLAG_READONLY | CONFIG_FLAG_NOSAVE },
		{ "AutoLodSoc", DATA_TYPE_BOOL, &s->info.AutoLodSoc, 0, 0, CONFIG_FLAG_READONLY | CONFIG_FLAG_NOSAVE },
		{ "Tm1", DATA_TYPE_BOOL, &s->info.Tm1, 0, 0, CONFIG_FLAG_READONLY | CONFIG_FLAG_NOSAVE },
		{ "Tm2", DATA_TYPE_BOOL, &s->info.Tm2, 0, 0, CONFIG_FLAG_READONLY | CONFIG_FLAG_NOSAVE },
		{ "ExtPwrDer", DATA_TYPE_BOOL, &s->info.ExtPwrDer, 0, 0, CONFIG_FLAG_READONLY | CONFIG_FLAG_NOSAVE },
		{ "ExtVfOk", DATA_TYPE_BOOL, &s->info.ExtVfOk, 0, 0, CONFIG_FLAG_READONLY | CONFIG_FLAG_NOSAVE },
		{ "GdOn", DATA_TYPE_BOOL, &s->info.GdOn, 0, 0, CONFIG_FLAG_READONLY | CONFIG_FLAG_NOSAVE },
		{ "GnOn", DATA_TYPE_BOOL, &s->info.GnOn, 0, 0, CONFIG_FLAG_READONLY | CONFIG_FLAG_NOSAVE },
		{ "Error", DATA_TYPE_BOOL, &s->info.Error, 0, 0, CONFIG_FLAG_READONLY | CONFIG_FLAG_NOSAVE },
		{ "Run", DATA_TYPE_BOOL, &s->info.Run, 0, 0, CONFIG_FLAG_READONLY | CONFIG_FLAG_NOSAVE },
		{ "BatFan", DATA_TYPE_BOOL, &s->info.BatFan, 0, 0, CONFIG_FLAG_READONLY | CONFIG_FLAG_NOSAVE },
		{ "AcdCir", DATA_TYPE_BOOL, &s->info.AcdCir, 0, 0, CONFIG_FLAG_READONLY | CONFIG_FLAG_NOSAVE },
		{ "MccBatFan", DATA_TYPE_BOOL, &s->info.MccBatFan, 0, 0, CONFIG_FLAG_READONLY | CONFIG_FLAG_NOSAVE },
		{ "MccAutoLod", DATA_TYPE_BOOL, &s->info.MccAutoLod, 0, 0, CONFIG_FLAG_READONLY | CONFIG_FLAG_NOSAVE },
		{ "Chp", DATA_TYPE_BOOL, &s->info.Chp, 0, 0, CONFIG_FLAG_READONLY | CONFIG_FLAG_NOSAVE },
		{ "ChpAdd", DATA_TYPE_BOOL, &s->info.ChpAdd, 0, 0, CONFIG_FLAG_READONLY | CONFIG_FLAG_NOSAVE },
		{ "SiComRemote", DATA_TYPE_BOOL, &s->info.SiComRemote, 0, 0, CONFIG_FLAG_READONLY | CONFIG_FLAG_NOSAVE },
		{ "OverLoad", DATA_TYPE_BOOL, &s->info.OverLoad, 0, 0, CONFIG_FLAG_READONLY | CONFIG_FLAG_NOSAVE },
		{ "ExtSrcConn", DATA_TYPE_BOOL, &s->info.ExtSrcConn, 0, 0, CONFIG_FLAG_READONLY | CONFIG_FLAG_NOSAVE },
		{ "Silent", DATA_TYPE_BOOL, &s->info.Silent, 0, 0, CONFIG_FLAG_READONLY | CONFIG_FLAG_NOSAVE },
		{ "Current", DATA_TYPE_BOOL, &s->info.Current, 0, 0, CONFIG_FLAG_READONLY | CONFIG_FLAG_NOSAVE },
		{ "FeedSelfC", DATA_TYPE_BOOL, &s->info.FeedSelfC, 0, 0, CONFIG_FLAG_READONLY | CONFIG_FLAG_NOSAVE },
		{ "Esave", DATA_TYPE_BOOL, &s->info.Esave, 0, 0, CONFIG_FLAG_READONLY | CONFIG_FLAG_NOSAVE },
		{ "TotLodPwr", DATA_TYPE_FLOAT, &s->info.TotLodPwr, 0, 0, CONFIG_FLAG_READONLY | CONFIG_FLAG_NOSAVE },
		{ "charging_proc", DATA_TYPE_BYTE, &s->info.charging_proc, 0, 0, CONFIG_FLAG_READONLY | CONFIG_FLAG_NOSAVE },
		{ "state", DATA_TYPE_BYTE, &s->info.state, 0, 0, CONFIG_FLAG_READONLY | CONFIG_FLAG_NOSAVE },
		{ "errmsg", DATA_TYPE_SHORT, &s->info.errmsg, 0, 0, CONFIG_FLAG_READONLY | CONFIG_FLAG_NOSAVE },
//unhandled: si_power_t ac2_volt
		{ "input_voltage", DATA_TYPE_FLOAT, &s->info.ac2_voltage, 0, 0, CONFIG_FLAG_READONLY | CONFIG_FLAG_NOSAVE },
		{ "input_frequency", DATA_TYPE_FLOAT, &s->info.ac2_frequency, 0, 0, CONFIG_FLAG_READONLY | CONFIG_FLAG_NOSAVE },
		{ "input_current", DATA_TYPE_FLOAT, &s->info.ac2_current, 0, 0, CONFIG_FLAG_READONLY | CONFIG_FLAG_NOSAVE },
		{ "PVPwrAt", DATA_TYPE_FLOAT, &s->info.PVPwrAt, 0, 0, CONFIG_FLAG_READONLY | CONFIG_FLAG_NOSAVE },
		{ "GdCsmpPwrAt", DATA_TYPE_FLOAT, &s->info.GdCsmpPwrAt, 0, 0, CONFIG_FLAG_READONLY | CONFIG_FLAG_NOSAVE },
		{ "GdFeedPwr", DATA_TYPE_FLOAT, &s->info.GdFeedPwr, 0, 0, CONFIG_FLAG_READONLY | CONFIG_FLAG_NOSAVE },
