
LIBNAME=solard
SRCS=init.c debug.c opts.c log.c utils.c getpath.c memory.c daemon.c homedir.c list.c types.c conv.c json.c parson.c cfg.c mqtt.c uuid.c message.c findconf.c getpid.c buffer.c tmpdir.c exec.c null.c module.c controller.c battery.c inverter.c devserver.c agent.c client.c

include ../Makefile.sd
