#!/bin/bash

DB=power

# Make sure the FIRST year has every date in it - not goig to mess with unions/etc and mysql doesnt do full join
first_year=$(mysql --database=${DB} -N -B -e "SELECT table_name FROM information_schema.tables WHERE table_schema = \"${DB}\" AND table_name LIKE \"usage_2%\" ORDER BY table_name LIMIT 1;" 2>/dev/null | sed 's:^usage_::')
if test -z "$first_year"; then
	echo "unable to find usage_2% table in db ${DB}"
	exit 1
fi
first_day=$(mysql --database=${DB} -N -B -e "SELECT DATE_FORMAT(date,\"%m-%d\") as \"date\" from usage_${first_year} order by date limit 1;" 2>/dev/null)
if test -z "${first_day}"; then
	echo "no records in $table_name?!?"
	exit 1
fi
day="01-01"
while test $day != "$first_day"
do
	mysql --database=${DB} -e "INSERT INTO usage_${first_year} (date) VALUES (\"${first_year}-${day} 00:00\");"
	day=$(date -d "${first_year}-${day} +1 day" +%m-%d)
done
