#!/bin/bash

conf=/opt/sd/etc/email.conf
if test ! -f $conf; then
	echo "error: $conf missing"
	exit 1
fi
eval $(cat $conf 2>/dev/null | grep ^TO=)
if test -z "$TO"; then
	echo "error: TO= missing in $conf"
	exit 1
fi
eval $(cat /opt/sd/etc/email.conf 2>/dev/null | grep ^FROM=)
test -z "$FROM" && FROM="Solar System <solar@home.net>"

tmp=/tmp/solar_report.tmp
rep=/tmp/rep.txt
uue=/tmp/rep.uue
#trap '{ rm -f $tmp $rep $uue; }' EXIT

day=$(date -d "yesterday" "+%m/%d/%Y")
/root/bin/rep > $rep
/root/bin/mkpdf
if test -f /tmp/rep.pdf; then
	base64 /tmp/rep.pdf > $uue
	rm -f /tmp/rep.pdf
fi

rm -f $tmp; touch $tmp

boundary="+++++BOUNDARY++++"

echo "Content-Type: multipart/mixed; boundary=${boundary}" >> $tmp
echo "MIME-Version: 1.0" >> $tmp
echo "From: ${FROM}" >> $tmp
#echo "To: ${TO}" >> $tmp
echo "Subject: Utility usage for $day" >> $tmp
echo "" >> $tmp

# This area is a comment
#printf "This is a multipart message in MIME format.\n" >> $tmp

# Message begins here
echo "--${boundary}" >> $tmp
echo "Content-type: text/html; charset=utf-8" >> $tmp
echo "MIME-Version: 1.0" >> $tmp
echo "Content-Transfer-Encoding: 7bit" >> $tmp
echo "" >> $tmp
#echo "<html><body><pre><font size=\"2\"><tt><font face=\"Courier New, Courier, mono\">data</font></tt></pre></body></html>" >> $tmp
echo "<html><body><pre><font size=\"2\"><tt><font face=\"Courier New, Courier, mono\">" >> $tmp
cat /tmp/rep.txt >> $tmp
echo "</font></tt></pre></body></html>" >> $tmp

echo "--${boundary}" >> $tmp
echo "Content-Type: application/pdf" >> $tmp
echo "MIME-Version: 1.0" >> $tmp
echo "Content-Transfer-Encoding: base64" >> $tmp
echo "Content-Disposition: attachment; filename=\"report.pdf\"" >> $tmp
echo "" >> $tmp
cat /tmp/rep.uue >> $tmp
echo "" >> $tmp

# End boundary
echo "--${boundary}--" >> $tmp

#cat $tmp
cat $tmp | /usr/sbin/sendmail $TO
