
LIBNAME=smanet
SRCS=busevents.c byteorder.c chanvalrepo.c defractionizer.c driver_layer.c feature_tests.c fractionizer.c getini.c iorequest.c transport.c libyasdi.c mastercmd.c mempool.c minmap.c minqueue.c netchannel.c netdevice.c netpacket.c objman.c os_linux.c plant.c prot_layer.c repository.c router.c scheduler.c smadata_layer.c smanet.c stateconfig.c statedetection.c stateident.c statereadchan.c statewritechan.c statistic_writer.c sunnynet.c timer.c tools.c ysecurity.c libyasdimaster.c main.c

include ../Makefile.sd
