
PROGNAME=jk
SRCS=main.c info.c read.c config.c
TRANSPORTS=bluetooth,ip,can,serial,rdev
#TRANSPORTS=ip,can,serial,rdev
#LIBS=-L. -lgattlib
#LIBS+=-lglib-2.0 -lpthread -lbluetooth -ldbus-1

include ../../Makefile.sd
